---
title: "tidy_data"
author: "Qinting Shen"
date: "2023-09-26"
output: github_document
---

```{r}
library(tidyverse)
```

## PULSE data
```{r}
pulse_df =
  haven::read_sas("data/public_pulse_data.sas7bdat")|>
  janitor::clean_names()|>
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl","00m")
  )
```

### learning assessment

```{r}
litters_wide = 
  read_csv("./data/FAS_litters.csv") |>
  janitor::clean_names() |>
  select(litter_number, ends_with("weight")) |> 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd", 
    values_to = "weight") 
mutate(
    gd = case_match(
      gd,
      "gd0_weight"  ~ 0,
      "gd18_weight" ~ 18
    ))
```



## LoTR

Import

```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")
```


```{r}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") |>
  relocate(movie) |> 
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything()) 

```

## revisit FAS

```{r}
litter_data = 
  read_csv("./data/FAS_litters.csv") |>
  janitor::clean_names() |>
  separate(group, into = c("dose", "day_of_tx"), sep = 3) |>
  relocate(litter_number) |>
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    dose = str_to_lower(dose))
```

## pups

```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv") |>
  janitor::clean_names() |> 
  mutate(
  sex = 
    case_match(
      sex, 
      1 ~ "male", 
      2 ~ "female"),
   sex = as.factor(sex))

```

